-- Phase 6: Wine Search Integration (tables + columns)
-- Adds fingerprinting fields, search cache, external IDs, provenance ratings, and metrics.
--
-- POST-MIGRATION STEPS (after backfill):
-- 1. Run: node src/db/scripts/backfill_fingerprints.js
-- 2. Review collision report
-- 3. If collisions exist: node src/db/scripts/backfill_fingerprints.js --nullify-duplicates
-- 4. Add unique index: node src/db/scripts/backfill_fingerprints.js --add-unique-index
--
-- The unique fingerprint index is NOT included here because existing data may have collisions.
-- It should only be created after running the backfill script and resolving collisions.

-- =============================================================================
-- Wines table extensions
-- =============================================================================
ALTER TABLE wines ADD COLUMN IF NOT EXISTS fingerprint TEXT;
ALTER TABLE wines ADD COLUMN IF NOT EXISTS fingerprint_version SMALLINT DEFAULT 1;
ALTER TABLE wines ADD COLUMN IF NOT EXISTS ratings_status TEXT DEFAULT 'not_attempted'
  CHECK (ratings_status IN ('not_attempted', 'attempted_failed', 'partial', 'complete'));
ALTER TABLE wines ADD COLUMN IF NOT EXISTS ratings_last_attempt_at TIMESTAMPTZ;
ALTER TABLE wines ADD COLUMN IF NOT EXISTS ratings_attempt_count SMALLINT DEFAULT 0;
ALTER TABLE wines ADD COLUMN IF NOT EXISTS ratings_next_retry_at TIMESTAMPTZ;

-- Non-unique index for queries (unique index added after backfill via script)
CREATE INDEX IF NOT EXISTS idx_wines_cellar_fingerprint ON wines(cellar_id, fingerprint);
CREATE INDEX IF NOT EXISTS idx_wines_cellar_ratings_status ON wines(cellar_id, ratings_status);

-- =============================================================================
-- Wine search cache (Phase 6 pipeline)
-- =============================================================================
CREATE TABLE IF NOT EXISTS wine_search_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cellar_id UUID NOT NULL REFERENCES cellars(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  query_hash TEXT NOT NULL,
  pipeline_version SMALLINT NOT NULL DEFAULT 1,
  search_result JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  last_hit_at TIMESTAMPTZ,
  UNIQUE(cellar_id, fingerprint, pipeline_version)
);

CREATE INDEX IF NOT EXISTS idx_wine_search_cache_expires ON wine_search_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_wine_search_cache_cellar ON wine_search_cache(cellar_id);

-- =============================================================================
-- External ID candidates
-- =============================================================================
CREATE TABLE IF NOT EXISTS wine_external_ids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id BIGINT NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  external_id TEXT NOT NULL,
  external_url TEXT,
  match_confidence REAL,
  status TEXT NOT NULL DEFAULT 'candidate'
    CHECK (status IN ('candidate', 'confirmed', 'rejected')),
  selected_by_user BOOLEAN DEFAULT FALSE,
  evidence JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wine_external_ids_confirmed
  ON wine_external_ids(wine_id, source) WHERE status = 'confirmed';
CREATE INDEX IF NOT EXISTS idx_wine_external_ids_lookup ON wine_external_ids(external_id, source);
CREATE INDEX IF NOT EXISTS idx_wine_external_ids_wine ON wine_external_ids(wine_id);

-- =============================================================================
-- Ratings with provenance (separate from awards ratings table)
-- =============================================================================
CREATE TABLE IF NOT EXISTS wine_source_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id BIGINT NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  rating_value REAL NOT NULL,
  rating_scale TEXT NOT NULL,
  review_count INTEGER,
  previous_rating_value REAL,
  captured_at TIMESTAMPTZ DEFAULT NOW(),
  source_url TEXT,
  extraction_method TEXT NOT NULL
    CHECK (extraction_method IN ('structured', 'regex', 'unlocker', 'claude', 'manual')),
  UNIQUE(wine_id, source)
);

CREATE INDEX IF NOT EXISTS idx_wine_source_ratings_wine_id ON wine_source_ratings(wine_id);
CREATE INDEX IF NOT EXISTS idx_wine_source_ratings_source ON wine_source_ratings(source);

-- =============================================================================
-- Search metrics
-- =============================================================================
CREATE TABLE IF NOT EXISTS search_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cellar_id UUID NOT NULL REFERENCES cellars(id) ON DELETE CASCADE,
  fingerprint TEXT,
  pipeline_version SMALLINT NOT NULL DEFAULT 1,
  latency_ms INTEGER,
  total_cost_cents INTEGER DEFAULT 0,
  extraction_method TEXT,
  match_confidence REAL,
  stop_reason TEXT,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_search_metrics_cellar ON search_metrics(cellar_id);
CREATE INDEX IF NOT EXISTS idx_search_metrics_created_at ON search_metrics(created_at);
