-- Sprint 3: Layer 0 Knowledge Base (Extend Existing)
-- Extends wine_search_cache for shared memory and adds public URL/extraction caches.

-- =============================================================================
-- Extend wine_search_cache for global/shared entries
-- =============================================================================
ALTER TABLE wine_search_cache
  ALTER COLUMN cellar_id DROP NOT NULL;

ALTER TABLE wine_search_cache
  ADD COLUMN IF NOT EXISTS cache_scope TEXT NOT NULL DEFAULT 'cellar'
    CHECK (cache_scope IN ('cellar', 'global'));

-- Ensure a single global cache entry per fingerprint/pipeline version
CREATE UNIQUE INDEX IF NOT EXISTS idx_wine_search_cache_global
  ON wine_search_cache (fingerprint, pipeline_version)
  WHERE cellar_id IS NULL AND cache_scope = 'global';

CREATE INDEX IF NOT EXISTS idx_wine_search_cache_scope
  ON wine_search_cache (cache_scope);

-- =============================================================================
-- Public URL cache (shared across cellars)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public_url_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  etag TEXT,
  last_modified TEXT,
  content_type TEXT,
  byte_size INTEGER,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  fetch_count INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'valid'
    CHECK (status IN ('valid', 'stale', 'error', 'gone'))
);

CREATE INDEX IF NOT EXISTS idx_public_url_cache_expires
  ON public_url_cache (expires_at) WHERE status = 'valid';

-- =============================================================================
-- Public extraction cache (shared across cellars)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public_extraction_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_cache_id BIGINT REFERENCES public_url_cache(id) ON DELETE CASCADE,
  extraction_method TEXT,
  extracted_at TIMESTAMPTZ DEFAULT NOW(),
  extracted_facts JSONB,
  confidence REAL,
  evidence_snippet TEXT,
  raw_content_hash TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_extraction_url_hash
  ON public_extraction_cache (url_cache_id, raw_content_hash);
