-- Migration 041: PostgreSQL-compatible versions of missing tables
-- Adds tables that were skipped during original migration (SQLite syntax)
-- Missing: drinking_window_defaults (008), wine_serving_temperatures (018)

-- =============================================================================
-- DRINKING WINDOW DEFAULTS (from 008_default_drinking_windows.sql)
-- =============================================================================

CREATE TABLE IF NOT EXISTS drinking_window_defaults (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Matching criteria (NULL = wildcard)
  grape TEXT,                              -- 'sangiovese', 'chardonnay', NULL for any
  style TEXT,                              -- 'appassimento', 'riserva', 'gran_reserva', NULL
  region TEXT,                             -- 'barolo', 'bordeaux', 'napa', NULL
  country TEXT,                            -- 'IT', 'FR', 'US', NULL
  colour TEXT,                             -- 'red', 'white', 'rose', 'sparkling', 'dessert'
  quality_tier TEXT,                       -- 'entry', 'mid', 'premium', 'icon', NULL

  -- Window parameters (years from vintage)
  drink_from_offset INTEGER NOT NULL,      -- years after vintage before ready
  drink_by_offset INTEGER NOT NULL,        -- years after vintage to consume by
  peak_offset INTEGER,                     -- years after vintage for peak (optional)

  -- Metadata
  confidence TEXT DEFAULT 'medium',        -- 'high', 'medium', 'low'
  notes TEXT,                              -- explanation
  priority INTEGER DEFAULT 100,            -- lower = more specific, matched first

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dwd_grape ON drinking_window_defaults(grape);
CREATE INDEX IF NOT EXISTS idx_dwd_style ON drinking_window_defaults(style);
CREATE INDEX IF NOT EXISTS idx_dwd_region ON drinking_window_defaults(region);
CREATE INDEX IF NOT EXISTS idx_dwd_colour ON drinking_window_defaults(colour);
CREATE INDEX IF NOT EXISTS idx_dwd_priority ON drinking_window_defaults(priority);


-- =============================================================================
-- RED GRAPES - SPECIFIC VARIETIES
-- =============================================================================

-- NEBBIOLO (Barolo, Barbaresco)
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('nebbiolo', 'barolo', 'riserva', 'red', 'premium', 10, 30, 18, 'high', 'Top Barolo Riserva needs decades', 10),
('nebbiolo', 'barolo', NULL, 'red', 'premium', 8, 25, 15, 'high', 'Barolo DOCG - classic development', 15),
('nebbiolo', 'barolo', NULL, 'red', 'mid', 5, 18, 10, 'high', 'Entry Barolo - earlier drinking', 20),
('nebbiolo', 'barbaresco', NULL, 'red', 'premium', 6, 20, 12, 'high', 'Barbaresco - slightly earlier than Barolo', 15),
('nebbiolo', 'barbaresco', NULL, 'red', 'mid', 4, 15, 8, 'high', 'Entry Barbaresco', 20),
('nebbiolo', 'langhe', NULL, 'red', NULL, 2, 8, 4, 'medium', 'Langhe Nebbiolo - drink younger', 25),
('nebbiolo', NULL, NULL, 'red', NULL, 3, 12, 6, 'medium', 'Generic Nebbiolo', 50);

-- SANGIOVESE (Chianti, Brunello, etc.)
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('sangiovese', 'brunello', 'riserva', 'red', 'premium', 10, 30, 18, 'high', 'Brunello Riserva - long-lived', 10),
('sangiovese', 'brunello', NULL, 'red', 'premium', 8, 25, 15, 'high', 'Brunello di Montalcino DOCG', 15),
('sangiovese', 'chianti_classico', 'gran_selezione', 'red', 'premium', 5, 18, 10, 'high', 'Chianti Classico Gran Selezione', 15),
('sangiovese', 'chianti_classico', 'riserva', 'red', 'mid', 4, 15, 8, 'high', 'Chianti Classico Riserva', 20),
('sangiovese', 'chianti_classico', NULL, 'red', 'mid', 2, 10, 5, 'high', 'Chianti Classico', 25),
('sangiovese', 'chianti', NULL, 'red', 'entry', 1, 5, 2, 'high', 'Basic Chianti - drink young', 30),
('sangiovese', 'romagna', 'riserva', 'red', 'mid', 3, 10, 5, 'medium', 'Romagna Sangiovese Riserva', 25),
('sangiovese', 'romagna', NULL, 'red', 'entry', 1, 6, 3, 'medium', 'Romagna Sangiovese', 30),
('sangiovese', NULL, 'appassimento', 'red', NULL, 2, 8, 4, 'medium', 'Appassimento style - richer, earlier peak', 20),
('sangiovese', NULL, NULL, 'red', NULL, 2, 8, 4, 'medium', 'Generic Sangiovese', 50);

-- PRIMITIVO / ZINFANDEL
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('primitivo', 'manduria', NULL, 'red', 'premium', 3, 12, 6, 'high', 'Primitivo di Manduria - structured', 15),
('primitivo', 'manduria', NULL, 'red', 'mid', 2, 8, 4, 'high', 'Standard Manduria', 20),
('primitivo', NULL, 'appassimento', 'red', NULL, 2, 10, 5, 'medium', 'Appassimento Primitivo', 20),
('primitivo', NULL, NULL, 'red', NULL, 1, 6, 3, 'medium', 'Generic Primitivo', 50),
('zinfandel', 'napa', NULL, 'red', 'premium', 3, 12, 6, 'medium', 'Napa Zinfandel', 20),
('zinfandel', 'sonoma', NULL, 'red', 'mid', 2, 10, 5, 'medium', 'Sonoma Zinfandel', 25),
('zinfandel', NULL, NULL, 'red', NULL, 1, 7, 3, 'medium', 'Generic Zinfandel', 50);

-- CABERNET SAUVIGNON
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('cabernet_sauvignon', 'bordeaux', NULL, 'red', 'icon', 15, 50, 25, 'high', 'First Growth / classified Bordeaux', 5),
('cabernet_sauvignon', 'bordeaux', NULL, 'red', 'premium', 8, 30, 15, 'high', 'Cru Bourgeois / quality Bordeaux', 15),
('cabernet_sauvignon', 'bordeaux', NULL, 'red', 'mid', 5, 15, 8, 'high', 'Generic Bordeaux', 25),
('cabernet_sauvignon', 'napa', NULL, 'red', 'icon', 10, 35, 18, 'high', 'Cult Napa Cabernet', 10),
('cabernet_sauvignon', 'napa', NULL, 'red', 'premium', 5, 20, 10, 'high', 'Premium Napa Cabernet', 20),
('cabernet_sauvignon', 'napa', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Standard Napa Cabernet', 30),
('cabernet_sauvignon', 'stellenbosch', NULL, 'red', 'premium', 5, 18, 10, 'medium', 'Premium Stellenbosch Cab', 20),
('cabernet_sauvignon', 'stellenbosch', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Standard Stellenbosch Cab', 30),
('cabernet_sauvignon', 'coonawarra', NULL, 'red', 'premium', 5, 20, 10, 'medium', 'Coonawarra Cabernet', 20),
('cabernet_sauvignon', 'margaret_river', NULL, 'red', 'premium', 5, 18, 10, 'medium', 'Margaret River Cabernet', 20),
('cabernet_sauvignon', NULL, NULL, 'red', 'premium', 5, 18, 10, 'medium', 'Premium Cabernet generic', 40),
('cabernet_sauvignon', NULL, NULL, 'red', 'mid', 3, 10, 5, 'medium', 'Mid-tier Cabernet', 45),
('cabernet_sauvignon', NULL, NULL, 'red', NULL, 2, 10, 5, 'low', 'Generic Cabernet Sauvignon', 50);

-- MERLOT
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('merlot', 'pomerol', NULL, 'red', 'icon', 10, 40, 20, 'high', 'Top Pomerol', 10),
('merlot', 'pomerol', NULL, 'red', 'premium', 6, 25, 12, 'high', 'Quality Pomerol', 15),
('merlot', 'saint_emilion', NULL, 'red', 'premium', 6, 25, 12, 'high', 'Saint-Emilion Grand Cru', 15),
('merlot', 'bordeaux', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Generic Bordeaux Merlot', 30),
('merlot', NULL, NULL, 'red', 'premium', 4, 15, 8, 'medium', 'Premium Merlot', 40),
('merlot', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Merlot', 50);

-- PINOT NOIR
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('pinot_noir', 'burgundy', NULL, 'red', 'icon', 10, 30, 18, 'high', 'Grand Cru Burgundy', 5),
('pinot_noir', 'burgundy', NULL, 'red', 'premium', 6, 20, 12, 'high', 'Premier Cru / Village Burgundy', 15),
('pinot_noir', 'burgundy', NULL, 'red', 'mid', 3, 12, 6, 'high', 'Bourgogne / Regional', 25),
('pinot_noir', 'oregon', NULL, 'red', 'premium', 4, 15, 8, 'medium', 'Oregon Pinot Noir', 20),
('pinot_noir', 'central_otago', NULL, 'red', 'premium', 3, 12, 6, 'medium', 'Central Otago Pinot', 20),
('pinot_noir', 'marlborough', NULL, 'red', 'mid', 2, 8, 4, 'medium', 'Marlborough Pinot', 25),
('pinot_noir', 'sonoma', NULL, 'red', 'premium', 3, 12, 6, 'medium', 'Sonoma Coast Pinot', 20),
('pinot_noir', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Pinot Noir', 50);

-- SYRAH / SHIRAZ
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('syrah', 'hermitage', NULL, 'red', 'icon', 10, 40, 20, 'high', 'Hermitage - extremely long-lived', 5),
('syrah', 'cote_rotie', NULL, 'red', 'premium', 8, 30, 15, 'high', 'Cote-Rotie', 10),
('syrah', 'cornas', NULL, 'red', 'premium', 6, 25, 12, 'high', 'Cornas', 15),
('syrah', 'rhone', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Northern Rhone generic', 30),
('shiraz', 'barossa', NULL, 'red', 'icon', 8, 30, 15, 'high', 'Icon Barossa Shiraz', 10),
('shiraz', 'barossa', NULL, 'red', 'premium', 5, 20, 10, 'high', 'Premium Barossa Shiraz', 15),
('shiraz', 'barossa', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Standard Barossa Shiraz', 25),
('shiraz', 'mclaren_vale', NULL, 'red', 'premium', 4, 18, 8, 'medium', 'McLaren Vale Shiraz', 20),
('shiraz', 'hunter_valley', NULL, 'red', 'premium', 5, 25, 12, 'medium', 'Hunter Valley Shiraz - ages well', 20),
('syrah', NULL, NULL, 'red', NULL, 3, 12, 6, 'low', 'Generic Syrah', 50),
('shiraz', NULL, NULL, 'red', NULL, 2, 10, 5, 'low', 'Generic Shiraz', 50);

-- GRENACHE / GARNACHA
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('grenache', 'chateauneuf', NULL, 'red', 'premium', 5, 20, 10, 'high', 'Chateauneuf-du-Pape', 15),
('grenache', 'rhone', NULL, 'red', 'mid', 3, 12, 6, 'medium', 'Southern Rhone', 25),
('garnacha', 'priorat', NULL, 'red', 'premium', 5, 20, 10, 'high', 'Priorat', 15),
('garnacha', 'carinena', 'gran_reserva', 'red', 'mid', 4, 12, 7, 'medium', 'Carinena Gran Reserva', 20),
('garnacha', 'carinena', 'reserva', 'red', 'mid', 3, 10, 5, 'medium', 'Carinena Reserva', 25),
('garnacha', 'carinena', NULL, 'red', 'entry', 1, 6, 3, 'medium', 'Carinena basic', 30),
('grenache', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Grenache', 50),
('garnacha', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Garnacha', 50);

-- TEMPRANILLO
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('tempranillo', 'rioja', 'gran_reserva', 'red', 'premium', 8, 25, 15, 'high', 'Rioja Gran Reserva', 10),
('tempranillo', 'rioja', 'reserva', 'red', 'mid', 5, 18, 10, 'high', 'Rioja Reserva', 15),
('tempranillo', 'rioja', 'crianza', 'red', 'mid', 3, 12, 6, 'high', 'Rioja Crianza', 20),
('tempranillo', 'rioja', 'joven', 'red', 'entry', 1, 4, 2, 'high', 'Rioja Joven - drink young', 25),
('tempranillo', 'ribera_del_duero', 'gran_reserva', 'red', 'premium', 8, 25, 15, 'high', 'Ribera Gran Reserva', 10),
('tempranillo', 'ribera_del_duero', 'reserva', 'red', 'mid', 5, 18, 10, 'high', 'Ribera Reserva', 15),
('tempranillo', 'ribera_del_duero', 'crianza', 'red', 'mid', 3, 12, 6, 'high', 'Ribera Crianza', 20),
('tempranillo', 'toro', NULL, 'red', 'premium', 5, 20, 10, 'medium', 'Toro - powerful Tempranillo', 20),
('tempranillo', NULL, NULL, 'red', NULL, 2, 10, 5, 'low', 'Generic Tempranillo', 50);

-- MALBEC
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('malbec', 'mendoza', NULL, 'red', 'icon', 5, 20, 10, 'high', 'Icon Mendoza Malbec', 10),
('malbec', 'mendoza', NULL, 'red', 'premium', 3, 15, 7, 'high', 'Premium Mendoza Malbec', 15),
('malbec', 'mendoza', NULL, 'red', 'mid', 2, 10, 5, 'high', 'Standard Mendoza Malbec', 25),
('malbec', 'uco_valley', NULL, 'red', 'premium', 4, 18, 8, 'high', 'Uco Valley - high altitude', 15),
('malbec', 'cahors', NULL, 'red', 'premium', 5, 20, 10, 'medium', 'Cahors Malbec', 20),
('malbec', NULL, NULL, 'red', NULL, 2, 10, 5, 'low', 'Generic Malbec', 50);

-- PINOTAGE
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('pinotage', 'stellenbosch', NULL, 'red', 'premium', 3, 15, 7, 'medium', 'Premium Stellenbosch Pinotage', 20),
('pinotage', 'stellenbosch', NULL, 'red', 'mid', 2, 10, 5, 'medium', 'Standard Pinotage', 30),
('pinotage', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Pinotage', 50);

-- CARMENERE
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('carmenere', 'chile', NULL, 'red', 'premium', 3, 12, 6, 'medium', 'Premium Chilean Carmenere', 20),
('carmenere', 'chile', NULL, 'red', 'mid', 2, 8, 4, 'medium', 'Standard Carmenere', 30),
('carmenere', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Carmenere', 50);

-- TOURIGA NACIONAL
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('touriga_nacional', 'douro', NULL, 'red', 'premium', 5, 20, 10, 'medium', 'Douro Touriga Nacional', 20),
('touriga_nacional', 'dao', NULL, 'red', 'premium', 4, 18, 8, 'medium', 'Dao Touriga Nacional', 25),
('touriga_nacional', NULL, NULL, 'red', NULL, 3, 12, 6, 'low', 'Generic Touriga Nacional', 50);

-- AGLIANICO
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('aglianico', 'taurasi', NULL, 'red', 'premium', 8, 25, 15, 'high', 'Taurasi DOCG - very tannic', 15),
('aglianico', 'aglianico_del_vulture', NULL, 'red', 'premium', 5, 20, 10, 'medium', 'Aglianico del Vulture', 20),
('aglianico', NULL, NULL, 'red', NULL, 4, 15, 8, 'low', 'Generic Aglianico', 50);

-- NERO D'AVOLA
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('nero_davola', 'sicily', NULL, 'red', 'premium', 3, 12, 6, 'medium', 'Premium Sicilian Nero d''Avola', 20),
('nero_davola', 'sicily', NULL, 'red', 'mid', 2, 8, 4, 'medium', 'Standard Nero d''Avola', 30),
('nero_davola', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Nero d''Avola', 50);

-- CORVINA (Amarone, Valpolicella)
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('corvina', 'amarone', NULL, 'red', 'premium', 8, 30, 15, 'high', 'Amarone della Valpolicella', 10),
('corvina', 'valpolicella', 'ripasso', 'red', 'mid', 3, 12, 6, 'high', 'Valpolicella Ripasso', 20),
('corvina', 'valpolicella', 'superiore', 'red', 'mid', 2, 10, 5, 'medium', 'Valpolicella Superiore', 25),
('corvina', 'valpolicella', NULL, 'red', 'entry', 1, 5, 2, 'medium', 'Basic Valpolicella', 30),
('corvina', NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Generic Corvina', 50);


-- =============================================================================
-- WHITE GRAPES - SPECIFIC VARIETIES
-- =============================================================================

-- CHARDONNAY
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('chardonnay', 'burgundy', NULL, 'white', 'icon', 5, 20, 10, 'high', 'Grand Cru White Burgundy', 5),
('chardonnay', 'burgundy', NULL, 'white', 'premium', 3, 12, 6, 'high', 'Premier Cru / Village Burgundy', 15),
('chardonnay', 'burgundy', NULL, 'white', 'mid', 2, 7, 4, 'high', 'Bourgogne Blanc', 25),
('chardonnay', 'chablis', 'grand_cru', 'white', 'premium', 5, 18, 10, 'high', 'Chablis Grand Cru', 10),
('chardonnay', 'chablis', 'premier_cru', 'white', 'mid', 3, 12, 6, 'high', 'Chablis Premier Cru', 15),
('chardonnay', 'chablis', NULL, 'white', 'mid', 2, 8, 4, 'high', 'Chablis Village', 20),
('chardonnay', 'napa', NULL, 'white', 'premium', 2, 8, 4, 'medium', 'Napa Chardonnay - oaked', 20),
('chardonnay', 'sonoma', NULL, 'white', 'mid', 2, 7, 3, 'medium', 'Sonoma Chardonnay', 25),
('chardonnay', 'margaret_river', NULL, 'white', 'premium', 2, 10, 5, 'medium', 'Margaret River Chardonnay', 20),
('chardonnay', NULL, 'unoaked', 'white', NULL, 1, 4, 2, 'medium', 'Unoaked Chardonnay - drink young', 30),
('chardonnay', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Chardonnay', 50);

-- SAUVIGNON BLANC
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('sauvignon_blanc', 'marlborough', NULL, 'white', 'mid', 1, 4, 2, 'high', 'Marlborough Sauvignon Blanc', 15),
('sauvignon_blanc', 'sancerre', NULL, 'white', 'premium', 1, 6, 3, 'high', 'Sancerre', 15),
('sauvignon_blanc', 'pouilly_fume', NULL, 'white', 'premium', 2, 8, 4, 'high', 'Pouilly-Fume', 15),
('sauvignon_blanc', 'bordeaux', NULL, 'white', 'premium', 2, 10, 5, 'medium', 'White Bordeaux (oaked)', 20),
('sauvignon_blanc', 'constantia', NULL, 'white', 'premium', 1, 6, 3, 'medium', 'Constantia Sauvignon Blanc', 20),
('sauvignon_blanc', NULL, NULL, 'white', NULL, 1, 4, 2, 'low', 'Generic Sauvignon Blanc', 50);

-- RIESLING
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('riesling', 'mosel', 'trockenbeerenauslese', 'white', 'icon', 10, 50, 25, 'high', 'TBA - virtually immortal', 5),
('riesling', 'mosel', 'auslese', 'white', 'premium', 5, 30, 15, 'high', 'Auslese - very long-lived', 10),
('riesling', 'mosel', 'spatlese', 'white', 'premium', 3, 20, 10, 'high', 'Spatlese', 15),
('riesling', 'mosel', 'kabinett', 'white', 'mid', 2, 12, 5, 'high', 'Kabinett', 20),
('riesling', 'rheingau', NULL, 'white', 'premium', 3, 18, 8, 'high', 'Rheingau Riesling', 15),
('riesling', 'alsace', 'grand_cru', 'white', 'premium', 5, 25, 12, 'high', 'Alsace Grand Cru', 10),
('riesling', 'alsace', NULL, 'white', 'mid', 2, 12, 5, 'high', 'Alsace Riesling', 20),
('riesling', 'clare_valley', NULL, 'white', 'premium', 3, 15, 7, 'medium', 'Clare Valley Riesling', 20),
('riesling', 'eden_valley', NULL, 'white', 'premium', 3, 15, 7, 'medium', 'Eden Valley Riesling', 20),
('riesling', NULL, 'dry', 'white', NULL, 2, 10, 5, 'medium', 'Dry Riesling generic', 40),
('riesling', NULL, 'sweet', 'white', NULL, 5, 25, 12, 'medium', 'Sweet Riesling generic', 40),
('riesling', NULL, NULL, 'white', NULL, 2, 10, 5, 'low', 'Generic Riesling', 50);

-- PINOT GRIGIO / PINOT GRIS
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('pinot_grigio', 'alto_adige', NULL, 'white', 'premium', 1, 5, 2, 'high', 'Alto Adige Pinot Grigio', 15),
('pinot_grigio', 'friuli', NULL, 'white', 'mid', 1, 4, 2, 'medium', 'Friuli Pinot Grigio', 20),
('pinot_gris', 'alsace', NULL, 'white', 'premium', 2, 10, 5, 'high', 'Alsace Pinot Gris - richer style', 15),
('pinot_gris', 'oregon', NULL, 'white', 'mid', 1, 5, 2, 'medium', 'Oregon Pinot Gris', 25),
('pinot_grigio', NULL, NULL, 'white', NULL, 1, 3, 1, 'low', 'Generic Pinot Grigio', 50),
('pinot_gris', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Pinot Gris', 50);

-- GEWURZTRAMINER
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('gewurztraminer', 'alsace', 'vendange_tardive', 'white', 'premium', 5, 20, 10, 'high', 'Alsace VT Gewurztraminer', 10),
('gewurztraminer', 'alsace', NULL, 'white', 'mid', 2, 8, 4, 'high', 'Alsace Gewurztraminer', 15),
('gewurztraminer', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Gewurztraminer', 50);

-- VIOGNIER
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('viognier', 'condrieu', NULL, 'white', 'premium', 2, 8, 4, 'high', 'Condrieu', 10),
('viognier', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Viognier', 50);

-- CHENIN BLANC
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('chenin_blanc', 'vouvray', 'moelleux', 'white', 'premium', 5, 30, 15, 'high', 'Vouvray Moelleux - very long-lived', 10),
('chenin_blanc', 'vouvray', 'sec', 'white', 'mid', 2, 10, 5, 'high', 'Vouvray Sec', 20),
('chenin_blanc', 'savennieres', NULL, 'white', 'premium', 5, 25, 12, 'high', 'Savennieres', 15),
('chenin_blanc', 'stellenbosch', NULL, 'white', 'premium', 2, 10, 5, 'medium', 'Old Vine Stellenbosch Chenin', 20),
('chenin_blanc', 'swartland', NULL, 'white', 'premium', 2, 10, 5, 'medium', 'Swartland Chenin Blanc', 20),
('chenin_blanc', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Chenin Blanc', 50);

-- GRUNER VELTLINER
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('gruner_veltliner', 'wachau', 'smaragd', 'white', 'premium', 3, 15, 7, 'high', 'Wachau Smaragd', 10),
('gruner_veltliner', 'wachau', 'federspiel', 'white', 'mid', 2, 8, 4, 'high', 'Wachau Federspiel', 15),
('gruner_veltliner', 'wachau', 'steinfeder', 'white', 'entry', 1, 3, 1, 'high', 'Wachau Steinfeder', 20),
('gruner_veltliner', NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'Generic Gruner Veltliner', 50);

-- ALBARINO
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('albarino', 'rias_baixas', NULL, 'white', 'premium', 1, 6, 3, 'high', 'Rias Baixas Albarino', 15),
('albarino', NULL, NULL, 'white', NULL, 1, 4, 2, 'low', 'Generic Albarino', 50);

-- VERDEJO
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('verdejo', 'rueda', NULL, 'white', 'mid', 1, 5, 2, 'high', 'Rueda Verdejo', 15),
('verdejo', NULL, NULL, 'white', NULL, 1, 4, 2, 'low', 'Generic Verdejo', 50);

-- VERMENTINO
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('vermentino', 'sardinia', NULL, 'white', 'mid', 1, 5, 2, 'medium', 'Sardinian Vermentino', 20),
('vermentino', 'liguria', NULL, 'white', 'mid', 1, 4, 2, 'medium', 'Ligurian Vermentino', 25),
('vermentino', NULL, NULL, 'white', NULL, 1, 4, 2, 'low', 'Generic Vermentino', 50);

-- SEMILLON
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('semillon', 'hunter_valley', NULL, 'white', 'premium', 5, 25, 12, 'high', 'Hunter Valley Semillon - ages remarkably', 10),
('semillon', 'bordeaux', NULL, 'white', 'premium', 3, 15, 7, 'medium', 'White Bordeaux Semillon blend', 20),
('semillon', NULL, NULL, 'white', NULL, 1, 6, 3, 'low', 'Generic Semillon', 50);


-- =============================================================================
-- ROSE WINES
-- =============================================================================

INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'provence', NULL, 'rose', 'premium', 1, 3, 1, 'high', 'Provence Rose', 15),
(NULL, 'provence', NULL, 'rose', 'mid', 1, 2, 1, 'high', 'Standard Provence Rose', 20),
(NULL, 'tavel', NULL, 'rose', 'premium', 1, 5, 2, 'high', 'Tavel - can age slightly', 15),
(NULL, 'navarra', NULL, 'rose', 'mid', 1, 2, 1, 'medium', 'Navarra Rosado', 25),
(NULL, NULL, NULL, 'rose', NULL, 1, 2, 1, 'medium', 'Generic Rose - drink young', 50);


-- =============================================================================
-- SPARKLING WINES
-- =============================================================================

INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'champagne', 'vintage', 'sparkling', 'icon', 10, 30, 18, 'high', 'Prestige Cuvee / Dom Perignon etc.', 5),
(NULL, 'champagne', 'vintage', 'sparkling', 'premium', 5, 20, 10, 'high', 'Vintage Champagne', 10),
(NULL, 'champagne', NULL, 'sparkling', 'mid', 1, 5, 2, 'high', 'NV Champagne', 20),
(NULL, 'franciacorta', 'riserva', 'sparkling', 'premium', 5, 15, 8, 'medium', 'Franciacorta Riserva', 15),
(NULL, 'franciacorta', NULL, 'sparkling', 'mid', 2, 8, 4, 'medium', 'Franciacorta', 25),
(NULL, 'english_sparkling', NULL, 'sparkling', 'premium', 3, 12, 6, 'medium', 'English Sparkling Wine', 20),
('cava', NULL, 'gran_reserva', 'sparkling', 'mid', 3, 10, 5, 'medium', 'Cava Gran Reserva', 20),
('cava', NULL, 'reserva', 'sparkling', 'mid', 2, 6, 3, 'medium', 'Cava Reserva', 25),
('cava', NULL, NULL, 'sparkling', 'entry', 1, 3, 1, 'medium', 'Basic Cava', 30),
(NULL, 'prosecco', NULL, 'sparkling', 'mid', 1, 2, 1, 'high', 'Prosecco - drink very young', 20),
(NULL, NULL, NULL, 'sparkling', NULL, 1, 4, 2, 'low', 'Generic Sparkling', 50);


-- =============================================================================
-- DESSERT / FORTIFIED WINES
-- =============================================================================

-- Sauternes & sweet Bordeaux
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'sauternes', NULL, 'dessert', 'icon', 15, 100, 40, 'high', 'Top Sauternes - essentially immortal', 5),
(NULL, 'sauternes', NULL, 'dessert', 'premium', 10, 50, 25, 'high', 'Quality Sauternes', 10),
(NULL, 'barsac', NULL, 'dessert', 'premium', 8, 40, 20, 'high', 'Barsac', 15);

-- Port
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'port', 'vintage', 'dessert', 'premium', 15, 60, 30, 'high', 'Vintage Port', 10),
(NULL, 'port', 'lbv', 'dessert', 'mid', 1, 15, 7, 'high', 'LBV Port', 20),
(NULL, 'port', 'tawny_aged', 'dessert', 'premium', 1, 50, NULL, 'high', 'Aged Tawny - no peak, stable', 15),
(NULL, 'port', 'ruby', 'dessert', 'entry', 1, 5, 2, 'high', 'Ruby Port', 30);

-- Sherry
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'sherry', 'fino', 'dessert', 'mid', 1, 2, 1, 'high', 'Fino/Manzanilla - drink immediately', 10),
(NULL, 'sherry', 'amontillado', 'dessert', 'mid', 1, 10, 5, 'high', 'Amontillado', 15),
(NULL, 'sherry', 'oloroso', 'dessert', 'mid', 1, 20, 10, 'high', 'Oloroso', 15),
(NULL, 'sherry', 'px', 'dessert', 'mid', 1, 30, 15, 'high', 'Pedro Ximenez', 15);

-- Madeira
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'madeira', NULL, 'dessert', 'premium', 1, 200, NULL, 'high', 'Madeira - virtually indestructible', 10);

-- Vin Santo
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'vin_santo', NULL, 'dessert', 'premium', 5, 30, 15, 'medium', 'Vin Santo', 20);

-- Tokaji
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, 'tokaji', 'aszu', 'dessert', 'premium', 10, 50, 25, 'high', 'Tokaji Aszu', 10);

-- Ice Wine
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
('icewine', NULL, NULL, 'dessert', 'premium', 5, 25, 12, 'medium', 'Ice Wine', 20);

-- Generic dessert
INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, NULL, NULL, 'dessert', NULL, 3, 20, 10, 'low', 'Generic Dessert Wine', 50);


-- =============================================================================
-- GENERIC FALLBACKS BY COLOUR (lowest priority)
-- =============================================================================

INSERT INTO drinking_window_defaults (grape, region, style, colour, quality_tier, drink_from_offset, drink_by_offset, peak_offset, confidence, notes, priority) VALUES
(NULL, NULL, NULL, 'red', 'icon', 8, 30, 15, 'low', 'Icon red wine - generic', 90),
(NULL, NULL, NULL, 'red', 'premium', 4, 15, 8, 'low', 'Premium red wine - generic', 92),
(NULL, NULL, NULL, 'red', 'mid', 2, 10, 5, 'low', 'Mid-tier red wine - generic', 94),
(NULL, NULL, NULL, 'red', 'entry', 1, 5, 2, 'low', 'Entry red wine - generic', 96),
(NULL, NULL, NULL, 'red', NULL, 2, 8, 4, 'low', 'Red wine - unknown tier', 98),

(NULL, NULL, NULL, 'white', 'icon', 5, 20, 10, 'low', 'Icon white wine - generic', 90),
(NULL, NULL, NULL, 'white', 'premium', 2, 10, 5, 'low', 'Premium white wine - generic', 92),
(NULL, NULL, NULL, 'white', 'mid', 1, 6, 3, 'low', 'Mid-tier white wine - generic', 94),
(NULL, NULL, NULL, 'white', 'entry', 1, 3, 1, 'low', 'Entry white wine - generic', 96),
(NULL, NULL, NULL, 'white', NULL, 1, 5, 2, 'low', 'White wine - unknown tier', 98),

(NULL, NULL, NULL, 'rose', NULL, 1, 2, 1, 'low', 'Rose - always drink young', 98),
(NULL, NULL, NULL, 'sparkling', NULL, 1, 4, 2, 'low', 'Sparkling - generic', 98),
(NULL, NULL, NULL, 'dessert', NULL, 3, 20, 10, 'low', 'Dessert wine - generic', 98);


-- =============================================================================
-- WINE SERVING TEMPERATURES (from 018_wine_serving_temperatures.sql)
-- =============================================================================

CREATE TABLE IF NOT EXISTS wine_serving_temperatures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_type TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  grape_varieties TEXT,
  regions TEXT,
  body TEXT,
  temp_min_celsius INTEGER NOT NULL,
  temp_max_celsius INTEGER NOT NULL,
  temp_min_fahrenheit INTEGER NOT NULL,
  temp_max_fahrenheit INTEGER NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_serving_temp_wine_type ON wine_serving_temperatures(wine_type);
CREATE INDEX IF NOT EXISTS idx_serving_temp_category ON wine_serving_temperatures(category);
CREATE INDEX IF NOT EXISTS idx_serving_temp_grape_varieties ON wine_serving_temperatures(grape_varieties);
CREATE INDEX IF NOT EXISTS idx_serving_temp_body ON wine_serving_temperatures(body);

-- =============================================
-- SPARKLING WINES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Prosecco', 'sparkling', 'charmat_method', 'Glera', 'Veneto, Italy', 'light', 5, 7, 41, 45, 'Serve very cold to preserve bubbles and fresh fruit character'),
('Cava', 'sparkling', 'traditional_method', 'Macabeo, Parellada, Xarel-lo', 'Catalonia, Spain', 'light-medium', 6, 8, 43, 46, 'Slightly warmer than Prosecco for traditional method complexity'),
('Cremant', 'sparkling', 'traditional_method', 'Various', 'France (Alsace, Loire, Burgundy)', 'light-medium', 6, 8, 43, 46, 'Traditional method sparkling, similar to Champagne service'),
('Champagne (NV)', 'sparkling', 'traditional_method', 'Chardonnay, Pinot Noir, Pinot Meunier', 'Champagne, France', 'medium', 6, 8, 43, 46, 'Non-vintage Champagne served cold to highlight freshness'),
('Champagne (Vintage)', 'sparkling', 'traditional_method', 'Chardonnay, Pinot Noir, Pinot Meunier', 'Champagne, France', 'medium-full', 8, 10, 46, 50, 'Vintage Champagne served slightly warmer to reveal complexity'),
('Champagne (Prestige Cuvee)', 'sparkling', 'traditional_method', 'Chardonnay, Pinot Noir, Pinot Meunier', 'Champagne, France', 'full', 10, 12, 50, 54, 'Dom Perignon, Krug etc. - warmer to express toast and biscuit notes'),
('Blanc de Blancs', 'sparkling', 'traditional_method', 'Chardonnay', 'Champagne, France', 'light-medium', 7, 9, 45, 48, '100% Chardonnay, served slightly cooler for acidity'),
('Blanc de Noirs', 'sparkling', 'traditional_method', 'Pinot Noir, Pinot Meunier', 'Champagne, France', 'medium', 8, 10, 46, 50, 'Fuller body from red grapes, slightly warmer service'),
('Franciacorta', 'sparkling', 'traditional_method', 'Chardonnay, Pinot Noir, Pinot Bianco', 'Lombardy, Italy', 'medium', 6, 8, 43, 46, 'Italian traditional method, similar to Champagne'),
('Sekt', 'sparkling', 'various', 'Riesling, Pinot Blanc, Pinot Noir', 'Germany, Austria', 'light-medium', 6, 8, 43, 46, 'German/Austrian sparkling wine'),
('Pet-Nat', 'sparkling', 'ancestral_method', 'Various', 'Various', 'light', 6, 9, 43, 48, 'Natural sparkling, serve cold but not ice cold'),
('Asti', 'sparkling', 'charmat_method', 'Moscato Bianco', 'Piedmont, Italy', 'light', 5, 7, 41, 45, 'Sweet sparkling, serve very cold'),
('Moscato d''Asti', 'sparkling', 'charmat_method', 'Moscato Bianco', 'Piedmont, Italy', 'light', 5, 7, 41, 45, 'Sweet sparkling, serve very cold'),
('Lambrusco', 'sparkling', 'charmat_method', 'Lambrusco varieties', 'Emilia-Romagna, Italy', 'light-medium', 8, 12, 46, 54, 'Red sparkling, can be served slightly warmer');

-- =============================================
-- WHITE WINES - LIGHT BODIED
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Sauvignon Blanc', 'white', 'light_crisp', 'Sauvignon Blanc', 'Loire, New Zealand, South Africa', 'light', 7, 10, 45, 50, 'Serve cold to preserve acidity and citrus/herbaceous notes'),
('Sancerre', 'white', 'light_crisp', 'Sauvignon Blanc', 'Loire, France', 'light-medium', 8, 10, 46, 50, 'Top Loire Sauvignon, slightly warmer for minerality'),
('Pouilly-Fume', 'white', 'light_crisp', 'Sauvignon Blanc', 'Loire, France', 'light-medium', 8, 10, 46, 50, 'Smoky Sauvignon, similar to Sancerre'),
('Marlborough Sauvignon Blanc', 'white', 'light_crisp', 'Sauvignon Blanc', 'Marlborough, New Zealand', 'light', 7, 9, 45, 48, 'Very aromatic, serve cold to preserve tropical fruit'),
('Pinot Grigio', 'white', 'light_crisp', 'Pinot Grigio', 'Northern Italy, Alsace', 'light', 7, 9, 45, 48, 'Light and refreshing, serve cold'),
('Pinot Gris', 'white', 'light_crisp', 'Pinot Gris', 'Alsace, Oregon', 'light-medium', 8, 10, 46, 50, 'Fuller style than Grigio'),
('Muscadet', 'white', 'light_crisp', 'Melon de Bourgogne', 'Loire, France', 'light', 7, 9, 45, 48, 'Bone dry, serve cold with shellfish'),
('Vinho Verde', 'white', 'light_crisp', 'Alvarinho, Loureiro, Arinto', 'Minho, Portugal', 'light', 6, 8, 43, 46, 'Often slightly sparkling, serve very cold'),
('Albarino', 'white', 'light_crisp', 'Albarino', 'Rias Baixas, Spain', 'light-medium', 7, 10, 45, 50, 'Aromatic Spanish white, cold service'),
('Picpoul de Pinet', 'white', 'light_crisp', 'Picpoul', 'Languedoc, France', 'light', 7, 9, 45, 48, 'Crisp Mediterranean white'),
('Vermentino', 'white', 'light_crisp', 'Vermentino', 'Sardinia, Liguria, Provence', 'light', 7, 10, 45, 50, 'Herbal and saline notes'),
('Verdejo', 'white', 'light_crisp', 'Verdejo', 'Rueda, Spain', 'light', 7, 9, 45, 48, 'Spanish alternative to Sauvignon Blanc'),
('Gruner Veltliner', 'white', 'light_crisp', 'Gruner Veltliner', 'Austria', 'light-medium', 8, 10, 46, 50, 'Peppery Austrian white'),
('Assyrtiko', 'white', 'light_crisp', 'Assyrtiko', 'Santorini, Greece', 'light-medium', 8, 10, 46, 50, 'High acid Greek white, volcanic minerality');

-- =============================================
-- WHITE WINES - AROMATIC
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Riesling (Dry)', 'white', 'aromatic', 'Riesling', 'Germany, Alsace, Austria', 'light-medium', 8, 10, 46, 50, 'Trocken/dry Riesling, cold to highlight acidity'),
('Riesling (Off-Dry)', 'white', 'aromatic', 'Riesling', 'Germany (Kabinett, Spatlese)', 'light-medium', 6, 8, 43, 46, 'Slightly sweet, serve colder to balance sweetness'),
('Riesling', 'white', 'aromatic', 'Riesling', 'Germany, Alsace, Australia', 'light-medium', 7, 10, 45, 50, 'General Riesling serving temperature'),
('Gewurztraminer', 'white', 'aromatic', 'Gewurztraminer', 'Alsace, Germany, Alto Adige', 'medium', 8, 11, 46, 52, 'Highly aromatic, not too cold to express lychee/rose'),
('Torrontes', 'white', 'aromatic', 'Torrontes', 'Argentina', 'light-medium', 7, 10, 45, 50, 'Floral Argentine white'),
('Muscat (Dry)', 'white', 'aromatic', 'Muscat varieties', 'Alsace, Australia', 'light', 7, 9, 45, 48, 'Grapey and floral, serve cold'),
('Viognier', 'white', 'aromatic', 'Viognier', 'Rhone, California, Australia', 'medium-full', 10, 13, 50, 55, 'Rich and aromatic, warmer to express apricot/peach'),
('Malvasia', 'white', 'aromatic', 'Malvasia varieties', 'Italy, Portugal, Spain', 'medium', 9, 12, 48, 54, 'Aromatic Mediterranean grape');

-- =============================================
-- WHITE WINES - FULL BODIED
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Chardonnay (Unoaked)', 'white', 'full_bodied', 'Chardonnay', 'Chablis, Macon, Australia', 'medium', 9, 11, 48, 52, 'Unoaked style, cooler to preserve freshness'),
('Chardonnay (Oaked)', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, California, Australia', 'full', 11, 14, 52, 57, 'Barrel-aged Chardonnay, warmer to express oak and butter'),
('Chardonnay', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, California, Australia', 'medium-full', 10, 13, 50, 55, 'General Chardonnay serving temperature'),
('White Burgundy (Village)', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'medium-full', 10, 12, 50, 54, 'Village level Burgundy'),
('White Burgundy (Premier/Grand Cru)', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'full', 12, 14, 54, 57, 'Top Burgundy whites need warmth for complexity'),
('Chablis', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'medium', 9, 11, 48, 52, 'Unoaked Burgundy Chardonnay'),
('Meursault', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'full', 12, 14, 54, 57, 'Rich and nutty, serve at higher end'),
('Montrachet', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'full', 12, 14, 54, 57, 'Grand Cru, maximum complexity at warmer temps'),
('Pouilly-Fuisse', 'white', 'full_bodied', 'Chardonnay', 'Burgundy, France', 'medium-full', 10, 13, 50, 55, 'Southern Burgundy Chardonnay'),
('Chateauneuf-du-Pape Blanc', 'white', 'full_bodied', 'Roussanne, Grenache Blanc', 'Rhone, France', 'full', 11, 13, 52, 55, 'Rich southern Rhone white'),
('White Rioja', 'white', 'full_bodied', 'Viura, Malvasia', 'Rioja, Spain', 'medium-full', 10, 13, 50, 55, 'Oaked style served warmer'),
('Chenin Blanc (Dry)', 'white', 'full_bodied', 'Chenin Blanc', 'Loire, South Africa', 'medium', 9, 12, 48, 54, 'Dry style Chenin'),
('Chenin Blanc (Oaked)', 'white', 'full_bodied', 'Chenin Blanc', 'South Africa', 'full', 11, 14, 52, 57, 'Barrel-fermented SA Chenin'),
('Chenin Blanc', 'white', 'full_bodied', 'Chenin Blanc', 'Loire, South Africa', 'medium', 9, 12, 48, 54, 'General Chenin Blanc serving temperature'),
('Semillon', 'white', 'full_bodied', 'Semillon', 'Hunter Valley, Bordeaux', 'medium-full', 10, 13, 50, 55, 'Ages beautifully, serve warmer when mature'),
('Fiano', 'white', 'full_bodied', 'Fiano', 'Campania, Italy', 'medium', 9, 12, 48, 54, 'Italian white with texture'),
('Greco di Tufo', 'white', 'full_bodied', 'Greco', 'Campania, Italy', 'medium', 9, 12, 48, 54, 'Mineral southern Italian white'),
('Arinto', 'white', 'full_bodied', 'Arinto', 'Portugal', 'medium', 9, 11, 48, 52, 'Crisp Portuguese white, ages well');

-- =============================================
-- ROSE WINES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Provence Rose', 'rose', 'pale_dry', 'Grenache, Cinsault, Syrah', 'Provence, France', 'light', 8, 10, 46, 50, 'Pale and delicate, serve cold'),
('Cotes de Provence', 'rose', 'pale_dry', 'Grenache, Cinsault, Syrah, Mourvedre', 'Provence, France', 'light', 8, 10, 46, 50, 'Classic Provencal rose'),
('Rose', 'rose', 'pale_dry', 'Various', 'Various', 'light', 8, 11, 46, 52, 'General rose serving temperature'),
('Tavel', 'rose', 'full_bodied', 'Grenache, Cinsault, Mourvedre', 'Rhone, France', 'medium-full', 10, 13, 50, 55, 'Full-bodied rose, can be served warmer'),
('Spanish Rosado', 'rose', 'medium', 'Garnacha, Tempranillo', 'Spain', 'medium', 9, 12, 48, 54, 'Darker Spanish rose'),
('Cerasuolo d''Abruzzo', 'rose', 'full_bodied', 'Montepulciano', 'Abruzzo, Italy', 'medium-full', 10, 13, 50, 55, 'Structured Italian rose, warmer service'),
('Bandol Rose', 'rose', 'medium', 'Mourvedre, Grenache, Cinsault', 'Provence, France', 'medium', 9, 12, 48, 54, 'More structured Provence rose'),
('White Zinfandel', 'rose', 'sweet', 'Zinfandel', 'California', 'light', 7, 9, 45, 48, 'Sweet rose, serve cold to balance sugar'),
('Rose Champagne', 'rose', 'sparkling', 'Pinot Noir, Chardonnay, Pinot Meunier', 'Champagne, France', 'medium', 7, 9, 45, 48, 'Pink Champagne, serve cold');

-- =============================================
-- ORANGE / SKIN-CONTACT WINES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Orange Wine (Light)', 'orange', 'short_maceration', 'Various white grapes', 'Various', 'light-medium', 10, 12, 50, 54, 'Short skin contact (3-7 days), serve cooler'),
('Orange Wine (Medium)', 'orange', 'medium_maceration', 'Various white grapes', 'Italy, Slovenia, Georgia', 'medium', 12, 14, 54, 57, 'Medium skin contact (1-3 weeks)'),
('Orange Wine (Full/Tannic)', 'orange', 'long_maceration', 'Ribolla Gialla, Rkatsiteli', 'Friuli, Georgia', 'full', 14, 18, 57, 64, 'Extended maceration, treat like light red'),
('Orange Wine', 'orange', 'skin_contact', 'Various white grapes', 'Various', 'medium', 12, 14, 54, 57, 'General orange wine serving temperature'),
('Georgian Amber Wine', 'orange', 'qvevri', 'Rkatsiteli, Mtsvane, Kisi', 'Georgia', 'medium-full', 12, 16, 54, 61, 'Traditional qvevri wines, warmer service'),
('Ramato (Pinot Grigio)', 'orange', 'skin_contact', 'Pinot Grigio', 'Friuli, Italy', 'light-medium', 10, 13, 50, 55, 'Copper-colored Pinot Grigio'),
('Ribolla Gialla (Skin Contact)', 'orange', 'long_maceration', 'Ribolla Gialla', 'Friuli, Italy', 'medium-full', 13, 16, 55, 61, 'Gravner/Radikon style, serve like light red');

-- =============================================
-- RED WINES - LIGHT BODIED
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Beaujolais', 'red', 'light_fruity', 'Gamay', 'Beaujolais, France', 'light', 12, 14, 54, 57, 'Light, fruity red, can be slightly chilled'),
('Beaujolais Nouveau', 'red', 'light_fruity', 'Gamay', 'Beaujolais, France', 'light', 10, 13, 50, 55, 'Very young wine, serve cool'),
('Beaujolais Cru', 'red', 'light_fruity', 'Gamay', 'Morgon, Fleurie, Moulin-a-Vent', 'light-medium', 13, 15, 55, 59, 'More structured Beaujolais, slightly warmer'),
('Gamay', 'red', 'light_fruity', 'Gamay', 'Beaujolais, Loire', 'light', 12, 14, 54, 57, 'Light and fruity, serve cool'),
('Valpolicella (Classico)', 'red', 'light_fruity', 'Corvina, Rondinella, Molinara', 'Veneto, Italy', 'light', 12, 14, 54, 57, 'Fresh, cherry-driven, serve cool'),
('Valpolicella', 'red', 'light_fruity', 'Corvina, Rondinella, Molinara', 'Veneto, Italy', 'light', 12, 14, 54, 57, 'Fresh, cherry-driven, serve cool'),
('Bardolino', 'red', 'light_fruity', 'Corvina, Rondinella, Molinara', 'Veneto, Italy', 'light', 12, 14, 54, 57, 'Light Lake Garda red'),
('Dolcetto', 'red', 'light_fruity', 'Dolcetto', 'Piedmont, Italy', 'light-medium', 13, 15, 55, 59, 'Soft tannins, fruity, serve cool'),
('Schiava', 'red', 'light_fruity', 'Schiava', 'Alto Adige, Italy', 'light', 12, 14, 54, 57, 'Very light, almost rose-like'),
('Zweigelt', 'red', 'light_fruity', 'Zweigelt', 'Austria', 'light-medium', 13, 15, 55, 59, 'Austrian red, cherry and spice'),
('Frappato', 'red', 'light_fruity', 'Frappato', 'Sicily, Italy', 'light', 12, 14, 54, 57, 'Light Sicilian red, serve cool'),
('Mencia', 'red', 'light_fruity', 'Mencia', 'Bierzo, Spain', 'light-medium', 13, 15, 55, 59, 'Spanish light red, floral notes'),
('Cinsault', 'red', 'light_fruity', 'Cinsault', 'South Africa, France', 'light', 12, 14, 54, 57, 'Light, refreshing red'),
('Tempranillo Joven', 'red', 'light_fruity', 'Tempranillo', 'Spain', 'light-medium', 12, 14, 54, 57, 'Young unoaked Tempranillo, serve cool'),
('Garnacha Joven', 'red', 'light_fruity', 'Garnacha', 'Spain', 'light-medium', 12, 14, 54, 57, 'Young Grenache, serve cool');

-- =============================================
-- RED WINES - MEDIUM BODIED
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Pinot Noir (Burgundy)', 'red', 'medium_elegant', 'Pinot Noir', 'Burgundy, France', 'medium', 14, 17, 57, 63, 'Red Burgundy, serve slightly cool to preserve elegance'),
('Pinot Noir (New World)', 'red', 'medium_elegant', 'Pinot Noir', 'California, Oregon, New Zealand', 'medium', 14, 16, 57, 61, 'Riper style Pinot, slightly cooler than Burgundy'),
('Pinot Noir', 'red', 'medium_elegant', 'Pinot Noir', 'Burgundy, California, New Zealand', 'medium', 14, 16, 57, 61, 'General Pinot Noir serving temperature'),
('Red Burgundy (Village)', 'red', 'medium_elegant', 'Pinot Noir', 'Burgundy, France', 'medium', 14, 16, 57, 61, 'Village level Burgundy'),
('Red Burgundy (Premier/Grand Cru)', 'red', 'medium_elegant', 'Pinot Noir', 'Burgundy, France', 'medium-full', 15, 17, 59, 63, 'Top Burgundy needs warmth for complexity'),
('Chianti', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium', 14, 16, 57, 61, 'Classic Tuscan red'),
('Chianti Classico', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium', 14, 16, 57, 61, 'Higher quality Chianti'),
('Chianti Classico Riserva', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium-full', 16, 18, 61, 64, 'Aged Chianti, warmer service'),
('Rosso di Montalcino', 'red', 'medium_structured', 'Sangiovese Grosso', 'Tuscany, Italy', 'medium', 14, 16, 57, 61, 'Baby Brunello'),
('Vino Nobile di Montepulciano', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium-full', 15, 17, 59, 63, 'Noble Tuscan wine'),
('Morellino di Scansano', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium', 14, 16, 57, 61, 'Coastal Tuscan Sangiovese'),
('Sangiovese', 'red', 'medium_structured', 'Sangiovese', 'Tuscany, Italy', 'medium', 14, 16, 57, 61, 'General Sangiovese serving temperature'),
('Sangiovese di Romagna', 'red', 'medium_structured', 'Sangiovese', 'Emilia-Romagna, Italy', 'medium', 14, 16, 57, 61, 'Romagna-style Sangiovese'),
('Barbera', 'red', 'medium_structured', 'Barbera', 'Piedmont, Italy', 'medium', 14, 16, 57, 61, 'High acid Piedmont red'),
('Barbera d''Asti', 'red', 'medium_structured', 'Barbera', 'Piedmont, Italy', 'medium', 14, 16, 57, 61, 'From Asti zone'),
('Barbera d''Alba', 'red', 'medium_structured', 'Barbera', 'Piedmont, Italy', 'medium-full', 15, 17, 59, 63, 'Often more structured than Asti'),
('Cotes du Rhone', 'red', 'medium_structured', 'Grenache, Syrah, Mourvedre', 'Rhone, France', 'medium', 14, 17, 57, 63, 'Southern Rhone blend'),
('Rioja Crianza', 'red', 'medium_structured', 'Tempranillo', 'Rioja, Spain', 'medium', 14, 17, 57, 63, 'Young oaked Rioja'),
('Rioja Reserva', 'red', 'medium_structured', 'Tempranillo', 'Rioja, Spain', 'medium-full', 16, 18, 61, 64, 'Aged Rioja needs warmth'),
('Rioja Gran Reserva', 'red', 'full_bodied', 'Tempranillo', 'Rioja, Spain', 'full', 17, 18, 63, 64, 'Long-aged Rioja, warmer service'),
('Rioja', 'red', 'medium_structured', 'Tempranillo', 'Rioja, Spain', 'medium', 15, 17, 59, 63, 'General Rioja serving temperature'),
('Tempranillo', 'red', 'medium_structured', 'Tempranillo', 'Spain', 'medium', 14, 17, 57, 63, 'General Tempranillo serving temperature'),
('Merlot', 'red', 'medium_structured', 'Merlot', 'Bordeaux, California, Chile', 'medium', 14, 17, 57, 63, 'Soft and approachable'),
('Zinfandel (Red)', 'red', 'medium_structured', 'Zinfandel', 'California', 'medium-full', 16, 18, 61, 64, 'Fruit-forward, can handle warmth'),
('Zinfandel', 'red', 'medium_structured', 'Zinfandel', 'California', 'medium-full', 16, 18, 61, 64, 'Fruit-forward, can handle warmth'),
('Grenache', 'red', 'medium_structured', 'Grenache', 'Spain, Rhone, Australia', 'medium', 14, 17, 57, 63, 'Spicy and fruity'),
('Garnacha', 'red', 'medium_structured', 'Garnacha', 'Spain', 'medium', 14, 17, 57, 63, 'Spicy and fruity'),
('Nero d''Avola', 'red', 'medium_structured', 'Nero d''Avola', 'Sicily, Italy', 'medium-full', 15, 17, 59, 63, 'Sicilian flagship red'),
('Montepulciano d''Abruzzo', 'red', 'medium_structured', 'Montepulciano', 'Abruzzo, Italy', 'medium', 14, 16, 57, 61, 'Soft central Italian red'),
('Carmenere', 'red', 'medium_structured', 'Carmenere', 'Chile', 'medium', 15, 17, 59, 63, 'Chilean signature red'),
('Portuguese Red (Light)', 'red', 'medium_structured', 'Various Portuguese grapes', 'Dao, Bairrada', 'medium', 14, 16, 57, 61, 'Lighter Portuguese styles'),
('Pinotage', 'red', 'medium_structured', 'Pinotage', 'South Africa', 'medium-full', 15, 17, 59, 63, 'SA signature grape'),
('Bobal', 'red', 'medium_structured', 'Bobal', 'Valencia, Spain', 'medium', 14, 16, 57, 61, 'Spanish native variety');

-- =============================================
-- RED WINES - FULL BODIED
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Cabernet Sauvignon', 'red', 'full_tannic', 'Cabernet Sauvignon', 'Bordeaux, Napa, Australia', 'full', 16, 18, 61, 64, 'Classic full-bodied red, serve just below room temp'),
('Bordeaux (Left Bank)', 'red', 'full_tannic', 'Cabernet Sauvignon, Merlot', 'Medoc, Graves, Pauillac', 'full', 17, 18, 63, 64, 'Cab-dominant Bordeaux'),
('Bordeaux (Right Bank)', 'red', 'full_tannic', 'Merlot, Cabernet Franc', 'Saint-Emilion, Pomerol', 'full', 16, 18, 61, 64, 'Merlot-dominant, slightly softer'),
('Bordeaux', 'red', 'full_tannic', 'Cabernet Sauvignon, Merlot, Cabernet Franc', 'Bordeaux, France', 'full', 16, 18, 61, 64, 'General Bordeaux serving temperature'),
('Napa Valley Cabernet', 'red', 'full_tannic', 'Cabernet Sauvignon', 'Napa Valley, California', 'full', 16, 18, 61, 64, 'Rich New World Cabernet'),
('Barolo', 'red', 'full_tannic', 'Nebbiolo', 'Piedmont, Italy', 'full', 16, 18, 61, 64, 'King of wines, needs warmth for aromatics'),
('Barolo Riserva', 'red', 'full_tannic', 'Nebbiolo', 'Piedmont, Italy', 'full', 17, 19, 63, 66, 'Long-aged Barolo, higher temp'),
('Barbaresco', 'red', 'full_tannic', 'Nebbiolo', 'Piedmont, Italy', 'full', 16, 18, 61, 64, 'Slightly more elegant than Barolo'),
('Nebbiolo', 'red', 'full_tannic', 'Nebbiolo', 'Piedmont, Italy', 'full', 16, 18, 61, 64, 'General Nebbiolo serving temperature'),
('Brunello di Montalcino', 'red', 'full_tannic', 'Sangiovese Grosso', 'Tuscany, Italy', 'full', 16, 18, 61, 64, 'Top Tuscan Sangiovese'),
('Brunello di Montalcino Riserva', 'red', 'full_tannic', 'Sangiovese Grosso', 'Tuscany, Italy', 'full', 17, 19, 63, 66, 'Extended aging, warmer'),
('Super Tuscan', 'red', 'full_tannic', 'Sangiovese, Cabernet, Merlot', 'Tuscany, Italy', 'full', 16, 18, 61, 64, 'International-style Tuscan blends'),
('Amarone della Valpolicella', 'red', 'full_rich', 'Corvina, Rondinella, Molinara', 'Veneto, Italy', 'full', 16, 18, 61, 64, 'Dried grape wine, rich and powerful'),
('Amarone', 'red', 'full_rich', 'Corvina, Rondinella, Molinara', 'Veneto, Italy', 'full', 16, 18, 61, 64, 'Dried grape wine, rich and powerful'),
('Ripasso', 'red', 'full_rich', 'Corvina, Rondinella', 'Veneto, Italy', 'medium-full', 15, 17, 59, 63, 'Baby Amarone style'),
('Primitivo', 'red', 'full_rich', 'Primitivo', 'Puglia, Italy', 'full', 16, 18, 61, 64, 'Southern Italian Zinfandel relative'),
('Appassimento', 'red', 'full_rich', 'Various', 'Italy', 'full', 16, 18, 61, 64, 'Dried grape wines from various regions'),
('Negroamaro', 'red', 'full_rich', 'Negroamaro', 'Puglia, Italy', 'full', 16, 18, 61, 64, 'Dark Puglian red'),
('Salice Salentino', 'red', 'full_rich', 'Negroamaro', 'Puglia, Italy', 'medium-full', 15, 17, 59, 63, 'Salento appellation'),
('Shiraz', 'red', 'full_rich', 'Shiraz', 'Australia, South Africa', 'full', 16, 18, 61, 64, 'Bold and spicy'),
('Syrah', 'red', 'full_rich', 'Syrah', 'Rhone, California', 'full', 16, 18, 61, 64, 'Bold and spicy'),
('Barossa Shiraz', 'red', 'full_rich', 'Shiraz', 'Barossa Valley, Australia', 'full', 17, 19, 63, 66, 'Very ripe, full Aussie Shiraz'),
('Northern Rhone Syrah', 'red', 'full_rich', 'Syrah', 'Hermitage, Cote-Rotie', 'full', 16, 18, 61, 64, 'Elegant and peppery'),
('Chateauneuf-du-Pape', 'red', 'full_rich', 'Grenache, Syrah, Mourvedre', 'Rhone, France', 'full', 16, 18, 61, 64, 'Southern Rhone flagship'),
('Gigondas', 'red', 'full_rich', 'Grenache, Syrah, Mourvedre', 'Rhone, France', 'full', 16, 18, 61, 64, 'Mini Chateauneuf'),
('Vacqueyras', 'red', 'full_rich', 'Grenache, Syrah, Mourvedre', 'Rhone, France', 'full', 16, 18, 61, 64, 'Southern Rhone Cru'),
('GSM Blend', 'red', 'full_rich', 'Grenache, Syrah, Mourvedre', 'Rhone, Australia', 'full', 16, 18, 61, 64, 'Grenache-Syrah-Mourvedre blend'),
('Ribera del Duero', 'red', 'full_tannic', 'Tempranillo (Tinto Fino)', 'Ribera del Duero, Spain', 'full', 16, 18, 61, 64, 'Powerful Spanish Tempranillo'),
('Ribera del Duero Reserva', 'red', 'full_tannic', 'Tempranillo', 'Ribera del Duero, Spain', 'full', 17, 18, 63, 64, 'Aged Ribera'),
('Toro', 'red', 'full_tannic', 'Tinta de Toro (Tempranillo)', 'Toro, Spain', 'full', 16, 18, 61, 64, 'Powerful, high alcohol Tempranillo'),
('Priorat', 'red', 'full_tannic', 'Garnacha, Carinena', 'Catalonia, Spain', 'full', 16, 18, 61, 64, 'Concentrated Catalan red'),
('Douro Red', 'red', 'full_rich', 'Touriga Nacional, Tinta Roriz', 'Douro, Portugal', 'full', 16, 18, 61, 64, 'Port grape red wine'),
('Touriga Nacional', 'red', 'full_rich', 'Touriga Nacional', 'Portugal', 'full', 16, 18, 61, 64, 'Portuguese flagship grape'),
('Alentejo Red', 'red', 'full_rich', 'Various Portuguese', 'Alentejo, Portugal', 'full', 16, 18, 61, 64, 'Southern Portuguese reds'),
('Dao Red', 'red', 'medium_structured', 'Touriga Nacional, Alfrocheiro', 'Dao, Portugal', 'medium-full', 15, 17, 59, 63, 'Elegant Portuguese reds'),
('Malbec', 'red', 'full_rich', 'Malbec', 'Argentina, Cahors', 'full', 16, 18, 61, 64, 'Argentine signature red'),
('Mendoza Malbec', 'red', 'full_rich', 'Malbec', 'Mendoza, Argentina', 'full', 16, 18, 61, 64, 'High altitude Malbec'),
('South African Bordeaux Blend', 'red', 'full_tannic', 'Cabernet, Merlot, Cab Franc', 'Stellenbosch, South Africa', 'full', 16, 18, 61, 64, 'Cape blends'),
('Cape Blend', 'red', 'full_tannic', 'Pinotage, Cabernet, Merlot', 'South Africa', 'full', 16, 18, 61, 64, 'South African signature blend'),
('Petite Sirah', 'red', 'full_tannic', 'Petite Sirah', 'California', 'full', 16, 18, 61, 64, 'Very dark and tannic'),
('Tannat', 'red', 'full_tannic', 'Tannat', 'Uruguay, Madiran', 'full', 16, 18, 61, 64, 'Extremely tannic'),
('Aglianico', 'red', 'full_tannic', 'Aglianico', 'Campania, Basilicata', 'full', 16, 18, 61, 64, 'Taurasi, Aglianico del Vulture'),
('Taurasi', 'red', 'full_tannic', 'Aglianico', 'Campania, Italy', 'full', 16, 18, 61, 64, 'Aglianico from Campania'),
('Sagrantino di Montefalco', 'red', 'full_tannic', 'Sagrantino', 'Umbria, Italy', 'full', 16, 18, 61, 64, 'Most tannic Italian grape');

-- =============================================
-- RED WINES - UNUSUAL/CURIOSITIES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Saperavi', 'red', 'full_rich', 'Saperavi', 'Georgia', 'full', 16, 18, 61, 64, 'Georgian teinturier grape'),
('Xinomavro', 'red', 'full_tannic', 'Xinomavro', 'Naoussa, Greece', 'full', 16, 18, 61, 64, 'Greek Nebbiolo equivalent'),
('Agiorgitiko', 'red', 'medium_structured', 'Agiorgitiko', 'Nemea, Greece', 'medium', 14, 17, 57, 63, 'Greek St. George grape'),
('Blaufrankisch', 'red', 'medium_structured', 'Blaufrankisch', 'Austria, Hungary', 'medium', 14, 17, 57, 63, 'Austrian/Hungarian red'),
('Kadarka', 'red', 'medium_structured', 'Kadarka', 'Hungary', 'medium', 14, 16, 57, 61, 'Hungarian native'),
('Plavac Mali', 'red', 'full_rich', 'Plavac Mali', 'Croatia', 'full', 16, 18, 61, 64, 'Croatian relative of Zinfandel');

-- =============================================
-- DESSERT WINES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Sauternes', 'dessert', 'botrytis', 'Semillon, Sauvignon Blanc', 'Bordeaux, France', 'full', 8, 10, 46, 50, 'Noble rot wine, cold to balance sweetness'),
('Barsac', 'dessert', 'botrytis', 'Semillon, Sauvignon Blanc', 'Bordeaux, France', 'full', 8, 10, 46, 50, 'Sauternes neighbor'),
('Tokaji Aszu', 'dessert', 'botrytis', 'Furmint, Harslevelu', 'Tokaj, Hungary', 'full', 10, 12, 50, 54, 'Hungarian noble rot, serve cool'),
('Tokaji', 'dessert', 'botrytis', 'Furmint, Harslevelu', 'Tokaj, Hungary', 'full', 10, 12, 50, 54, 'Hungarian noble rot, serve cool'),
('Trockenbeerenauslese (TBA)', 'dessert', 'botrytis', 'Riesling, other', 'Germany, Austria', 'full', 8, 10, 46, 50, 'Ultra-sweet German wine'),
('Beerenauslese (BA)', 'dessert', 'botrytis', 'Riesling, other', 'Germany, Austria', 'full', 8, 10, 46, 50, 'Sweet German wine'),
('Auslese', 'dessert', 'late_harvest', 'Riesling', 'Germany', 'medium', 8, 10, 46, 50, 'Late harvest, varying sweetness'),
('Ice Wine', 'dessert', 'ice_wine', 'Riesling, Vidal', 'Canada, Germany', 'full', 8, 10, 46, 50, 'Frozen grape wine, serve cold'),
('Eiswein', 'dessert', 'ice_wine', 'Riesling, Vidal', 'Germany, Austria', 'full', 8, 10, 46, 50, 'Frozen grape wine, serve cold'),
('Vin Santo', 'dessert', 'dried_grape', 'Trebbiano, Malvasia', 'Tuscany, Italy', 'full', 12, 14, 54, 57, 'Italian dried grape dessert wine'),
('Passito', 'dessert', 'dried_grape', 'Various', 'Italy', 'full', 10, 14, 50, 57, 'Dried grape wines'),
('Muscat de Beaumes-de-Venise', 'dessert', 'vin_doux_naturel', 'Muscat', 'Rhone, France', 'medium', 8, 10, 46, 50, 'Sweet fortified Muscat'),
('Moscatel de Setubal', 'dessert', 'fortified', 'Moscatel', 'Setubal, Portugal', 'full', 10, 12, 50, 54, 'Portuguese Muscat'),
('Late Harvest Riesling', 'dessert', 'late_harvest', 'Riesling', 'Various', 'medium', 8, 10, 46, 50, 'Sweet Riesling'),
('Late Harvest', 'dessert', 'late_harvest', 'Various', 'Various', 'medium', 8, 10, 46, 50, 'General late harvest wine'),
('Pedro Ximenez (PX)', 'dessert', 'fortified', 'Pedro Ximenez', 'Jerez, Spain', 'full', 12, 14, 54, 57, 'Extremely sweet sherry'),
('Recioto della Valpolicella', 'dessert', 'dried_grape', 'Corvina', 'Veneto, Italy', 'full', 12, 14, 54, 57, 'Sweet Amarone style'),
('Recioto di Soave', 'dessert', 'dried_grape', 'Garganega', 'Veneto, Italy', 'medium', 10, 12, 50, 54, 'Sweet white Veneto wine');

-- =============================================
-- FORTIFIED WINES
-- =============================================

INSERT INTO wine_serving_temperatures (wine_type, category, subcategory, grape_varieties, regions, body, temp_min_celsius, temp_max_celsius, temp_min_fahrenheit, temp_max_fahrenheit, notes) VALUES
('Fino Sherry', 'fortified', 'dry', 'Palomino', 'Jerez, Spain', 'light', 7, 9, 45, 48, 'Dry sherry, serve very cold like white wine'),
('Fino', 'fortified', 'dry', 'Palomino', 'Jerez, Spain', 'light', 7, 9, 45, 48, 'Dry sherry, serve very cold like white wine'),
('Manzanilla', 'fortified', 'dry', 'Palomino', 'Sanlucar, Spain', 'light', 7, 9, 45, 48, 'Coastal fino style'),
('Amontillado', 'fortified', 'medium', 'Palomino', 'Jerez, Spain', 'medium', 10, 13, 50, 55, 'Aged fino, slightly warmer'),
('Oloroso', 'fortified', 'medium', 'Palomino', 'Jerez, Spain', 'full', 12, 14, 54, 57, 'Rich oxidative sherry'),
('Palo Cortado', 'fortified', 'medium', 'Palomino', 'Jerez, Spain', 'full', 12, 14, 54, 57, 'Rare sherry style'),
('Cream Sherry', 'fortified', 'sweet', 'Palomino, PX', 'Jerez, Spain', 'full', 10, 12, 50, 54, 'Sweet sherry'),
('Sherry', 'fortified', 'various', 'Palomino, PX', 'Jerez, Spain', 'medium', 10, 13, 50, 55, 'General sherry serving temperature'),
('Ruby Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 14, 16, 57, 61, 'Young sweet Port'),
('Tawny Port (10-20 year)', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 12, 14, 54, 57, 'Aged tawny, serve cool'),
('Tawny Port (30-40 year)', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 14, 16, 57, 61, 'Very old tawny, slightly warmer'),
('Tawny Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 12, 14, 54, 57, 'Aged tawny, serve cool'),
('Vintage Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 16, 18, 63, 64, 'Vintage declared Port, serve like red'),
('Vintage/Vintage Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 16, 18, 63, 64, 'Vintage declared Port, serve like red'),
('Late Bottled Vintage (LBV) Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 14, 16, 57, 61, 'Ready-to-drink vintage style'),
('LBV Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 14, 16, 57, 61, 'Ready-to-drink vintage style'),
('Port', 'fortified', 'sweet', 'Touriga Nacional, etc.', 'Douro, Portugal', 'full', 14, 16, 57, 61, 'General Port serving temperature'),
('White Port', 'fortified', 'various', 'White grapes', 'Douro, Portugal', 'light-medium', 8, 10, 46, 50, 'Aperitif style, serve cold'),
('Rose Port', 'fortified', 'sweet', 'Red grapes', 'Douro, Portugal', 'light-medium', 8, 10, 46, 50, 'Pink Port, serve cold'),
('Madeira (Sercial)', 'fortified', 'dry', 'Sercial', 'Madeira, Portugal', 'medium', 10, 13, 50, 55, 'Driest Madeira'),
('Madeira (Verdelho)', 'fortified', 'medium_dry', 'Verdelho', 'Madeira, Portugal', 'medium', 12, 14, 54, 57, 'Off-dry Madeira'),
('Madeira (Bual/Boal)', 'fortified', 'medium_sweet', 'Bual', 'Madeira, Portugal', 'full', 14, 16, 57, 61, 'Medium-sweet Madeira'),
('Madeira (Malmsey/Malvasia)', 'fortified', 'sweet', 'Malvasia', 'Madeira, Portugal', 'full', 14, 16, 57, 61, 'Sweetest Madeira'),
('Madeira', 'fortified', 'various', 'Various', 'Madeira, Portugal', 'medium-full', 12, 15, 54, 59, 'General Madeira serving temperature'),
('Marsala (Dry)', 'fortified', 'dry', 'Grillo, Catarratto', 'Sicily, Italy', 'medium', 10, 12, 50, 54, 'Dry Sicilian fortified'),
('Marsala (Sweet)', 'fortified', 'sweet', 'Grillo, Catarratto', 'Sicily, Italy', 'full', 12, 14, 54, 57, 'Sweet Marsala'),
('Marsala', 'fortified', 'various', 'Grillo, Catarratto', 'Sicily, Italy', 'medium', 11, 13, 52, 55, 'General Marsala serving temperature'),
('Banyuls', 'fortified', 'sweet', 'Grenache', 'Roussillon, France', 'full', 14, 16, 57, 61, 'French sweet fortified'),
('Maury', 'fortified', 'sweet', 'Grenache', 'Roussillon, France', 'full', 14, 16, 57, 61, 'French vin doux naturel'),
('Rutherglen Muscat', 'fortified', 'sweet', 'Muscat', 'Victoria, Australia', 'full', 14, 16, 57, 61, 'Australian fortified Muscat'),
('Commandaria', 'fortified', 'sweet', 'Xynisteri, Mavro', 'Cyprus', 'full', 12, 14, 54, 57, 'Ancient Cypriot wine');
