-- Migration: Add cellar_id to user_settings for multi-tenant support
-- Previously user_settings was a single-user table with just (key, value)
-- Now it needs to be scoped per-cellar
-- NOTE: Made idempotent with IF EXISTS/IF NOT EXISTS clauses

-- Step 1: Rename old table if it exists (skip if already migrated)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_settings_old') THEN
    DROP TABLE user_settings_old;
  END IF;
END $$;

-- Step 2: Ensure user_settings has cellar_id column
-- If table exists without cellar_id, we need to recreate it
DO $$
BEGIN
  -- Check if user_settings exists but lacks cellar_id
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_settings')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                     WHERE table_name = 'user_settings' AND column_name = 'cellar_id') THEN
    -- Rename old table
    ALTER TABLE user_settings RENAME TO user_settings_old_temp;

    -- Create new table with cellar_id
    CREATE TABLE user_settings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cellar_id UUID NOT NULL,
      key TEXT NOT NULL,
      value TEXT NOT NULL,
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(cellar_id, key)
    );

    -- Drop temp table
    DROP TABLE user_settings_old_temp;
  END IF;
END $$;

-- Step 3: Ensure table exists (in case it was never created)
CREATE TABLE IF NOT EXISTS user_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cellar_id UUID NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cellar_id, key)
);

-- Step 4: Create index if not exists
CREATE INDEX IF NOT EXISTS idx_user_settings_cellar ON user_settings(cellar_id);
