-- Migration: Add cellar_id to user_settings for multi-tenant support
-- Previously user_settings was a single-user table with just (key, value)
-- Now it needs to be scoped per-cellar

-- Step 1: Rename old table
ALTER TABLE user_settings RENAME TO user_settings_old;

-- Step 2: Create new table with cellar_id
CREATE TABLE user_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cellar_id UUID NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cellar_id, key)
);

CREATE INDEX idx_user_settings_cellar ON user_settings(cellar_id);

-- Step 3: Drop old table (settings will be recreated per-cellar as needed)
-- Note: We intentionally don't migrate old data since it was not cellar-scoped
DROP TABLE user_settings_old;
